/* IS NULL */

SELECT * FROM BOOKS WHERE AUTHOR_FNAME IS NOT NULL;  /* PROVIDES VALUES WHICH ARE NOT NULL */

SELECT * FROM BOOKS WHERE AUTHOR_FNAME IS NULL; /* PROVIDES A NULL VALUE */

DELETE FROM BOOKS WHERE title IS NULL;

SELECT * FROM books WHERE title IS NOT NULL;