/* TIME FUNCTIONS */

/* HOUR*/

SELECT name , birthtime , HOUR(BIRTHDT) FROM PEOPLE;

/* minute */

SELECT MINUTE(BIRTHDT) FROM PEOPLE;

/* SECOND */

SELECT SECOND(BIRTHTIME) FROM PEOPLE;

/* TIME */

SELECT TIME(BIRTHDT) FROM PEOPLE;

SELECT TIME(BIRTHDT) , HOUR(BIRTHTIME) , MINUTE(BIRTHDT) , SECOND(BIRTHTIME) FROM PEOPLE;

/* FORMATTING DATES */

SELECT NAME , CONCAT (MONTHNAME(BIRTHDATE) , ' ' , DAY(BIRTHDT) , ' ' , YEAR(BIRTHDATE)) FROM PEOPLE;

/* FORMATTING FUNCTIONS */ /* mysql documentation reference manual */

SELECT birthdate , DATE_FORMAT(BIRTHDATE , '%b' )  from people;

select date_format(birthdate , '%c' ) from people;

SELECT DATE_FORMAT(birthdate , '%M') FROM people; 

SELECT CONCAT ( DATE_FORMAT(BIRTHDATE , '%M') , ' ' , DATE_FORMAT(birthdate , '%d') ,' ' , DATE_FORMAT(birthdate , '%Y') , ' ' , DATE_FORMAT(BIRTHDATE , '%W') ) AS 'BIRTHDATE AND DAY' FROM people;
 
 /* TIME FORMAT */
 
 SELECT TIME_FORMAT(BIRTHDT , '%H  %I %S ') FROM PEOPLE ;
 
 SELECT TIME_FORMAT(BIRTHDT , '%r') FROM people; 
 
 SELECT birthdt , DATE_FORMAT(birthdt , 'BORN ON : %r') FROM PEOPLE; 
 
 
 /* DATE MATH */
 
 /* DATEDIFF */
 
 SELECT BIRTHDT , DATEDIFF(CURDATE() , BIRTHDATE) FROM PEOPLE; /* days between two dates */
 
 select datediff(curdate() , curdate()); /* 0 */
 
 /* dateadd */
 
 SELECT DATE_ADD(CURDATE() , INTERVAL 7 YEAR);
 
 SELECT DATE_ADD(CURDATE() , INTERVAL 1 MONTH);
 
 /* DATE_SUB */
 
 SELECT DATE_SUB(CURDATE() , INTERVAL 1 MONTH); /* 1 MONTH AGO */
 
SELECT CONCAT(DATE_ADD(BIRTHDATE , INTERVAL 25 YEAR ) , ' ' , DATE_FORMAT(DATE_ADD(BIRTHDATE , INTERVAL 25 YEAR), '%W')) FROM PEOPLE;

/* TIME MATH ALSO HAS SAME FUCNTIONS LIKE :

ADDTIME , SUBTIME */

SELECT TIMEDIFF(CURTIME() , '09:00:00'); /* 4 HOURS OF DIFFERENCE */

SELECT NOW() - INTERVAL 21 YEAR;

SELECT NOW() - BIRTHDATE FROM PEOPLE;


 